import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import { NextUIProvider } from "@nextui-org/react";
import QueryClientWrapper from "@/components/Blogs/QueryClientWrapper";
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientWrapper>
          <NextUIProvider>
            <NavbarComponent className="dark text-foreground bg-dark-900" />
            <main className="dark text-foreground bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 min-h-screen">
              {children}
            </main>
          </NextUIProvider>
        </QueryClientWrapper>
        <SpeedInsights />
      </body>
    </html>
  );
}
